image: python:3.7

.python:
  before_script:
    - export RDLTR_DB_TEST_URL=sqlite:///rdltr_test.db
  script:
    - python setup.py test

python-3.6:
  extends: .python
  image: python:3.6

python-3.7:
  before_script:
    - pip install coveralls
  extends: .python
  script:
    - python setup.py test
    - echo "SUCCESS" > .job_status
  after_script:
    - if [ "$(cat .job_status)" == "SUCCESS" ]; then GIT_BRANCH="${CI_COMMIT_REF_NAME}" coveralls; fi

python-3.8:
  extends: .python
  image: python:3.8
