image: python:3.11

stages:
  - tests
  - selenium

.python:
  stage: tests
  before_script:
    - pip install -e .[test]
  script:
    - pytest rdltr/tests/tests --cov rdltr --cov-report term-missing

lint:
  extends: .python
  script:
    - pytest --isort --black -m "isort or black" rdltr
    - flake8 rdltr

type-check:
  extends: .python
  script:
    - mypy rdltr

python-3.8:
  extends: .python
  image: python:3.8

python-3.9:
  extends: .python
  image: python:3.9

python-3.10:
  extends: .python
  image: python:3.10

python-3.11:
  stage: tests
  before_script:
    - pip install -e .[test]
    - pip install coveralls
    - echo "FAILED" > .job_status
  script:
    - pytest rdltr/tests/tests --cov rdltr --cov-report term-missing
    - echo "SUCCESS" > .job_status
  after_script:
    - if [ "$(cat .job_status)" == "SUCCESS" ]; then GIT_BRANCH="${CI_COMMIT_REF_NAME}" coveralls; fi

firefox:
  stage: selenium
  services:
    - name: selenium/standalone-firefox
      alias: selenium
  variables:
    RDLTR_HOST: '0.0.0.0'
    RDLTR_SETTINGS: 'rdltr.config.TestingConfig'
    RDLTR_DB_TEST_URL: 'sqlite:////tmp/rdltr_test.db'
  before_script:
    - pip install -e .[test]
  script:
    - rdltr_db
    - setsid nohup rdltr > nohup.out &
    - export RDLTR_HOST=$(hostname --ip-address)
    - sleep 5
    - pytest rdltr/tests/ui_tests --driver Remote --capability browserName firefox --host selenium --port 4444
