image: python:3.7

.python:
  before_script:
    - export RDLTR_DB_TEST_URL=sqlite:///rdltr_test.db
    - pip install -e .[test]
  script:
    - pytest rdltr/tests/tests --cov rdltr --cov-report term-missing

python-3.6:
  extends: .python
  image: python:3.6

python-3.7:
  before_script:
    - pip install coveralls
  extends: .python
  script:
    - pytest rdltr/tests/tests --cov rdltr --cov-report term-missing
    - echo "SUCCESS" > .job_status
  after_script:
    - if [ "$(cat .job_status)" == "SUCCESS" ]; then GIT_BRANCH="${CI_COMMIT_REF_NAME}" coveralls; fi

python-3.8:
  extends: .python
  image: python:3.8
