language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - dist: xenial
      python: 3.7

install:
  - pip install coveralls

before_script:
  - export RDLTR_DB_TEST_URL=sqlite:///rdltr_test.db

script:
  - python setup.py test

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then coveralls;
    fi
