HOST = 0.0.0.0
PORT = 5000
PROJECT_NAME=rdltr
APP_PATH = $(PWD)/$(PROJECT_NAME)

export FLASK_APP = $(PROJECT_NAME)
export FLASK_ENV=development
export RDLTR_LOG=$(PROJECT_NAME).log
export RDLTR_SETTINGS=$(PROJECT_NAME).config.DevelopmentConfig
export RDLTR_DB_URL=sqlite:////$(APP_PATH)/$(PROJECT_NAME).db
export RDLTR_DB_TEST_URL=sqlite:////$(APP_PATH)/$(PROJECT_NAME)_test.db
export RDLTR_ALLOW_REGISTRATION=true

PYTHON_VERSION ?= python3.7
VENV = $(PWD)/.venv
PIP = $(VENV)/bin/pip
PYTHON = $(VENV)/bin/python
PYTEST = $(VENV)/bin/py.test
FLASK = $(VENV)/bin/flask
GUNICORN = $(VENV)/bin/gunicorn
ISORT = $(VENV)/bin/isort
BLACK = $(VENV)/bin/black

NPM ?= yarn
