HOST = 0.0.0.0
PORT = 5000
PROJECT_NAME=rdltr
APP_PATH = $(PWD)/$(PROJECT_NAME)

export FLASK_APP = $(PROJECT_NAME)
export FLASK_ENV=development
export APP_LOG=$(PROJECT_NAME).log

PYTHON_VERSION ?= python3.6
VENV = $(PWD)/.venv
PIP = $(VENV)/bin/pip
PYTHON = $(VENV)/bin/python
PYTEST = $(VENV)/bin/py.test
FLASK = $(VENV)/bin/flask
COV = $(VENV)/bin/python-codacy-coverage
ISORT = $(VENV)/bin/isort
